### ISSUE TITLE
tezos_sentry_version/tezos_private_version

### ISSUE THREAD

**Issue by denver-s** [hodl-dot-farm/tezos-on-gke#9]
What are these variables? Should they be set to "latest"?

**Comment by hodl-dot-farm** [comment]
You may set them to "mainnet" but it's not recommended ! In the past, I had
them set up this way, but then they merged the new storage. That required
to run a command to upgrade the storage and my baker broke because of this.
Since then, I hardcode a specific container version. I recommend you do the
same, and you manually upgrade the version once in a while. I just pushed a
change that makes it more clear in the variable description.

**Comment by denver-s** [comment]
May I suggest to set "mainnet" as default value in order to help others?

**Comment by hodl-dot-farm** [comment]
done. Thanks!
